### ISSUE TITLE
MVP 1 - User Auth ready for review

### ISSUE THREAD

**Issue by emikyu** [emikyu/Nekobook#2]

**Comment by jmeyer90** [comment]
To be resolved:

Homepage:
- Facebook has a larger logo on the top left of the page.
- Facebook has a larger gap between the two columns.
- Facebook has a smaller font size and smaller icons in the left columns..
- The smaller font in the left column is not just a different font-weight and size, but a different color as well.
- Facebook default birthday is today's date 25 years ago, not January 1st.
- Include a footer at the bottom of your page. Instead of having different languages, this is where you can have links to your github, linkedIn, etc. 
- Upon further review, Facebook does not have a username but first name and last name. Please make these adjustments in your frontend and backend.

**Comment by emikyu** [comment]
> To be resolved:
> 
> Homepage:
> 
> * Facebook has a larger logo on the top left of the page. - **done, changed from 28px to 34px**

> * Facebook has a larger gap between the two columns. - **Tripled check this, and I think the gap was the same (565px for LHS and 399px for RHS, with 980px column in the middle), except for I used "neko friends" instead of just "friends" in the hook text on the LHS - I've removed the "neko" bit so things look closure to the look and feel & put the hook inside the div so the width matches that of FB**

> * Facebook has a smaller font size and smaller icons in the left columns.. - **Changed the <li> font size from 16px to 15px to match; the hook seems to be the same across FB and clone; slightly decreased icon size (by around ~6px in height)**

> * The smaller font in the left column is not just a different font-weight and size, but a different color as well. - ** Changed the <li> font color to a slightly different color - from black to #333333, for better contrast with background" **

> * Facebook default birthday is today's date 25 years ago, not January 1st. - ** Revised accordingly courtesy of the Date object**

> * Include a footer at the bottom of your page. Instead of having different languages, this is where you can have links to your github, linkedIn, etc. - ** Included footer & styled to match clone cover scheme & FB concept**

> * Upon further review, Facebook does not have a username but first name and last name. Please make these adjustments in your frontend and backend. - ** Adjusted frontend and backend... username is now optional, last name is now required for sign in **

** I've also migrated again & reseeded the DB. New live version has been deployed on Heroku at [https://nekobook.herokuapp.com/](url) **

**Comment by jmeyer90** [comment]
Looks great! Please continue with your next MVP.
